// Subsets the web fonts to the characters the site actually uses and writes
// public/fonts/*.woff2 plus src/styles/fonts.css.
//
// Usage: node scripts/build-fonts.mjs   (runs automatically before `dev` and `build`)
//
// Korean fonts are large, and the stock unicode-range subsets made the page
// download ~36 files / 1.2 MB of fonts. Every character in src/ is collected,
// so new copy is covered as long as this script runs before the build.
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import subsetFont from 'subset-font';

const root = path.resolve('.');
const outDir = path.join(root, 'public/fonts');
const cssOut = path.join(root, 'src/styles/fonts.css');

const SERIF = {
  family: 'Noto Serif KR Variable',
  css: 'node_modules/@fontsource-variable/noto-serif-kr/index.css',
  weight: { min: 300, max: 500 },
  prefix: 'serif',
};
const SANS = {
  family: 'Pretendard Variable',
  file: 'node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2',
  weight: { min: 400, max: 500 },
  prefix: 'sans',
};

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(p);
    else if (/\.(astro|ts|css|md|mjs|json)$/.test(entry.name)) yield p;
  }
}

const codepoints = new Set();
for (let cp = 0x20; cp <= 0x7e; cp++) codepoints.add(cp);
for (const ch of '\u00a0·–—‘’“”…〈〉°') codepoints.add(ch.codePointAt(0));
for await (const file of walk(path.join(root, 'src'))) {
  if (file === cssOut) continue;
  for (const ch of await readFile(file, 'utf8')) {
    const cp = ch.codePointAt(0);
    if (cp > 0x7e && cp !== 0xfeff) codepoints.add(cp);
  }
}

const hex = (n) => n.toString(16).toUpperCase();
const toRanges = (cps) => {
  const sorted = [...cps].sort((a, b) => a - b);
  const out = [];
  for (let i = 0; i < sorted.length; i++) {
    let j = i;
    while (j + 1 < sorted.length && sorted[j + 1] === sorted[j] + 1) j++;
    out.push(i === j ? `U+${hex(sorted[i])}` : `U+${hex(sorted[i])}-${hex(sorted[j])}`);
    i = j;
  }
  return out.join(',');
};
const parseRanges = (s) =>
  s.split(',').map((r) => {
    const [a, b] = r.trim().replace(/^U\+/i, '').split('-');
    if (a.includes('?')) return [parseInt(a.replace(/\?/g, '0'), 16), parseInt(a.replace(/\?/g, 'F'), 16)];
    return [parseInt(a, 16), parseInt(b ?? a, 16)];
  });

const hash = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, 10);
const text = (cps) => String.fromCodePoint(...[...cps].sort((a, b) => a - b));

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const faces = [];
const emit = async ({ family, weight, prefix }, buf, cps, name) => {
  const file = `${prefix}-${name}.${hash(buf)}.woff2`;
  await writeFile(path.join(outDir, file), buf);
  faces.push({ family, weight, file, cps, bytes: buf.length });
};

// Serif: the stock files are already split by unicode-range. When ranges overlap the
// last @font-face wins, so each character is assigned to the last file that covers it.
const serifCss = await readFile(path.join(root, SERIF.css), 'utf8');
const blocks = [...serifCss.matchAll(/@font-face\s*{([^}]*)}/g)].map(([, body]) => ({
  src: body.match(/url\(([^)]+)\)/)[1].replace(/['"]/g, ''),
  ranges: parseRanges(body.match(/unicode-range:\s*([^;]+);/)[1]),
}));
const owner = new Map();
for (const cp of codepoints) {
  for (let i = blocks.length - 1; i >= 0; i--) {
    if (blocks[i].ranges.some(([a, b]) => cp >= a && cp <= b)) {
      owner.set(cp, i);
      break;
    }
  }
}
const byBlock = new Map();
for (const [cp, i] of owner) byBlock.set(i, [...(byBlock.get(i) ?? []), cp]);
for (const [i, cps] of [...byBlock].sort(([a], [b]) => a - b)) {
  const source = await readFile(path.join(root, path.dirname(SERIF.css), blocks[i].src));
  const buf = await subsetFont(source, text(cps), { targetFormat: 'woff2', variationAxes: { wght: SERIF.weight } });
  await emit(SERIF, buf, cps, String(i));
}

// Sans: Pretendard ships a full variable font, so it becomes a single file.
{
  const source = await readFile(path.join(root, SANS.file));
  const buf = await subsetFont(source, text(codepoints), { targetFormat: 'woff2', variationAxes: { wght: SANS.weight } });
  await emit(SANS, buf, codepoints, 'all');
}

const css = faces
  .map(
    (f) => `@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${f.weight.min} ${f.weight.max};
  font-display: swap;
  src: url("/fonts/${f.file}") format("woff2");${f.family === SERIF.family ? `\n  unicode-range: ${toRanges(f.cps)};` : ''}
}`,
  )
  .join('\n\n');
await writeFile(cssOut, `/* Generated by scripts/build-fonts.mjs — do not edit by hand. */\n\n${css}\n`);

const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
const total = (family) => faces.filter((f) => f.family === family).reduce((a, f) => a + f.bytes, 0);
console.log(
  `fonts: ${codepoints.size} characters · serif ${faces.filter((f) => f.family === SERIF.family).length} files ${kb(total(SERIF.family))} · sans ${kb(total(SANS.family))}`,
);
